# -*- coding: utf-8 -*-
"""MultimodalDeepLearningForBioExergame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRVa58k4t6Bub8Nf09ZSFJSqa9OxbrGR
"""

import os
import math
import random
from pathlib import Path

import numpy as np
import pandas as pd
import cv2
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers, losses, callbacks
from sklearn.model_selection import train_test_split

SEED = 42
random.seed(SEED); np.random.seed(SEED); tf.random.set_seed(SEED)

# Paths
BASE = "/content/drive/MyDrive/HCI Project/Datasets/ibdts_processed_data/ibdts_processed_data"
VIDEO_DIR = os.path.join(BASE, "3D_Motion_Videos")
HR_DIR    = os.path.join(BASE, "hr")
PERF_DIR  = os.path.join(BASE, "acc")  # folder with performance CSVs

# Video config
WINDOW_SEC = 4.0
N_FRAMES   = 16              # frames per 4s window (down from 128)
IMG_SIZE   = (128, 128)      # H, W
BATCH_SIZE = 8
EPOCHS     = 20

# Heart-rate intensity bins
HR_BINS = [0, 90, 130, 200]
HR_CLASS_NAMES = ["low", "medium", "high"]
NUM_HR_CLASSES = len(HR_CLASS_NAMES)

# Difficulty/load proxy classes
DIFF_CLASS_NAMES = ["low", "medium", "high"]
NUM_DIFF_CLASSES = len(DIFF_CLASS_NAMES)

def get_video_info(video_path):
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS)
    frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()
    return {"fps": fps, "frames": frames}

def load_hr_csv(hr_path):
    df = pd.read_csv(hr_path)
    # find HR column (same logic as before)
    if 'HR' in df.columns:
        hr_col = 'HR'
    else:
        num_cols = df.select_dtypes(include='number').columns
        if len(num_cols) == 0:
            raise ValueError(f"No numeric columns found in {hr_path}")
        if 'time_sec' in num_cols and len(num_cols) > 1:
            hr_col = [c for c in num_cols if c != 'time_sec'][0]
        else:
            hr_col = num_cols[0]
    return df, hr_col

def interval_mean_hr(hr_df, hr_col, start_sec, end_sec):
    # identical to your previous function
    if 'time_sec' in hr_df.columns:
        window = hr_df[(hr_df['time_sec'] >= start_sec) &
                       (hr_df['time_sec'] < end_sec)]
        if len(window) > 0:
            return float(window[hr_col].mean())
        t = hr_df['time_sec'].values
        v = hr_df[hr_col].values
        q_times = np.array([
            max(min(start_sec, t[-1]), t[0]),
            max(min(end_sec, t[-1]), t[0])
        ])
        iq = np.interp(q_times, t, v)
        return float(iq.mean())
    else:
        start_idx = int(math.floor(start_sec))
        end_idx   = int(math.ceil(end_sec))
        start_idx = max(start_idx, 0)
        end_idx   = min(end_idx, len(hr_df))
        if start_idx >= end_idx:
            return float(hr_df.iloc[-1][hr_col])
        return float(hr_df.iloc[start_idx:end_idx][hr_col].mean())

def hr_to_class(hr_value):
    return int(np.digitize(hr_value, HR_BINS) - 1)

def load_perf_csv(perf_path):
    """
    perf_path CSV has columns:
    'interval' like '0-4s', '4-8s', ...
    'LE','IE','LH','IH','LE_Error','IE_Error','LH_Error','IH_Error'
    """
    df = pd.read_csv(perf_path)
    # parse start_sec and end_sec from 'interval' column
    starts = []
    ends   = []
    for s in df['interval']:
        # assumes '0-4s' pattern
        part = s.replace('s', '')
        a, b = part.split('-')
        starts.append(float(a))
        ends.append(float(b))
    df['start_sec'] = starts
    df['end_sec']   = ends
    return df

LABEL_MAP = {
    "le": "LE",
    "ie": "IE",
    "lh": "LH",
    "ih": "IH",
}

def load_perf_csv(perf_path):
    df = pd.read_csv(perf_path)
    # Expect a column named 'interval' like '0-4s'
    starts, ends = [], []
    for s in df['interval']:
        s = str(s).replace('s', '')   # '0-4s' -> '0-4'
        a, b = s.split('-')
        starts.append(float(a))
        ends.append(float(b))
    df['start_sec'] = starts
    df['end_sec']   = ends
    return df

def build_window_index(video_dir, hr_dir, perf_dir):
    records = []

    for v in Path(video_dir).glob("*.mp4"):
        video_path = str(v)
        stem = v.stem        # e.g. 'p1_ie'
        parts = stem.split("_")
        participant = parts[0]   # 'p1'
        cond       = parts[1]    # 'ie', 'lh', etc.

        hr_path   = Path(hr_dir)   / f"{stem}_hr.csv"         # p1_ie_hr.csv
        perf_path = Path(perf_dir) / f"{participant}_accuracy.csv"  # p1_accuracy.csv

        if not hr_path.exists() or not perf_path.exists():
            # print for debugging if needed
            # print("Skip", stem, "hr_exists:", hr_path.exists(), "perf_exists:", perf_path.exists())
            continue

        info = get_video_info(video_path)
        fps  = info["fps"]
        total_frames = info["frames"]
        total_sec = total_frames / fps

        hr_df, hr_col   = load_hr_csv(hr_path)
        perf_df         = load_perf_csv(perf_path)

        # Which accuracy column to use for this video
        acc_col = LABEL_MAP.get(cond.lower(), None)
        if acc_col is None or acc_col not in perf_df.columns:
            # print("No matching accuracy column for", stem)
            continue

        for _, row in perf_df.iterrows():
            start_sec = float(row['start_sec'])
            end_sec   = float(row['end_sec'])

            if end_sec > total_sec:
                continue

            start_f = int(round(start_sec * fps))
            end_f   = int(round(end_sec   * fps))

            # HR intensity label
            hr_mean  = interval_mean_hr(hr_df, hr_col, start_sec, end_sec)
            hr_class = hr_to_class(hr_mean)

            # Performance for this video type
            perf = float(row[acc_col])

            records.append({
                "video_path": video_path,
                "start_frame": start_f,
                "end_frame": end_f,
                "start_sec": start_sec,
                "end_sec": end_sec,
                "hr_mean": hr_mean,
                "hr_class": hr_class,
                "perf": perf,
                "participant": participant,
                "cond": cond,
            })

    return records

window_index = build_window_index(VIDEO_DIR, HR_DIR, PERF_DIR)
len(window_index)

from pathlib import Path

print("VIDEO_DIR:", VIDEO_DIR)
print("HR_DIR   :", HR_DIR)
print("PERF_DIR :", PERF_DIR)

print("\nVideos:")
for p in Path(VIDEO_DIR).glob("*.mp4"):
    print(" ", p.name)

print("\nHR CSVs:")
for p in Path(HR_DIR).glob("*.csv"):
    print(" ", p.name)

print("\nAccuracy CSVs:")
for p in Path(PERF_DIR).glob("*.csv"):
    print(" ", p.name)

import collections

def add_difficulty_labels(records):
    # Group by participant
    by_p = collections.defaultdict(list)
    for r in records:
        by_p[r["participant"]].append(r)

    # For each participant, compute normalized HR and performance
    for p, recs in by_p.items():
        hr_vals   = np.array([r["hr_mean"] for r in recs])
        perf_vals = np.array([r["perf"]    for r in recs])

        # simple z-score normalization
        hr_mean_p, hr_std_p   = hr_vals.mean(), max(hr_vals.std(), 1e-6)
        perf_mean_p, perf_std_p = perf_vals.mean(), max(perf_vals.std(), 1e-6)

        for r in recs:
            r["hr_norm"]   = (r["hr_mean"] - hr_mean_p) / hr_std_p
            r["perf_norm"] = (r["perf"]    - perf_mean_p) / perf_std_p

    # Now assign difficulty/load proxy classes via heuristic thresholds
    def assign_diff_class(perf_norm, hr_norm):
        # Example rules; tune thresholds empirically
        # Low difficulty: very good perf, low HR
        if perf_norm >  0.5 and hr_norm <  0.0:
            return 0  # low
        # High difficulty: low perf, high HR
        if perf_norm < -0.5 and hr_norm >  0.0:
            return 2  # high
        # Otherwise medium
        return 1

    for r in records:
        r["diff_class"] = assign_diff_class(r["perf_norm"], r["hr_norm"])

    return records

window_index = add_difficulty_labels(window_index)

participants = sorted({r["participant"] for r in window_index})
train_p, rest = train_test_split(participants, test_size=0.3, random_state=SEED)
val_p, test_p = train_test_split(rest, test_size=0.5, random_state=SEED)

def filter_by_part(records, parts):
    return [r for r in records if r["participant"] in parts]

train_records = filter_by_part(window_index, set(train_p))
val_records   = filter_by_part(window_index, set(val_p))
test_records  = filter_by_part(window_index, set(test_p))

train_records[0]

def sample_clip_from_video(video_path, start_frame, end_frame, n_frames=N_FRAMES):
    cap = cv2.VideoCapture(video_path)
    idxs = np.linspace(start_frame, end_frame - 1, n_frames, dtype=int)

    frames = []
    for idx in idxs:
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ok, frame = cap.read()
        if not ok:
            frame = np.zeros((*IMG_SIZE, 3), dtype=np.uint8)
        else:
            frame = cv2.resize(frame, IMG_SIZE[::-1])
            frame = frame[..., ::-1]  # BGR to RGB
        frames.append(frame / 255.0)

    cap.release()
    return np.stack(frames).astype(np.float32)  # (T, H, W, 3)

def extract_hr_seq(hr_df, hr_col, start_sec, end_sec, step=1.0):
    # sample HR at 1 Hz using interpolation
    t0, t1 = start_sec, end_sec
    times = np.arange(t0, t1, step)
    if len(times) == 0:
        times = np.array([t0])

    if 'time_sec' in hr_df.columns:
        t = hr_df['time_sec'].values
        v = hr_df[hr_col].values
    else:
        # assume 1Hz, index -> seconds
        t = np.arange(len(hr_df))
        v = hr_df[hr_col].values

    # clamp
    times_clamped = np.clip(times, t.min(), t.max())
    hr_values = np.interp(times_clamped, t, v).astype(np.float32)
    return hr_values  # shape (T_hr,)

from functools import lru_cache

@lru_cache(maxsize=None)
def cached_hr_df(video_stem):
    hr_path = Path(HR_DIR) / f"{video_stem}_hr.csv"
    df, hr_col = load_hr_csv(hr_path)
    return df, hr_col

def multimodal_generator(records):
    recs = records.copy()
    random.shuffle(recs)

    for r in recs:
        video_path  = r["video_path"]
        start_frame = r["start_frame"]
        end_frame   = r["end_frame"]
        start_sec   = r["start_sec"]
        end_sec     = r["end_sec"]

        # Video
        clip = sample_clip_from_video(video_path, start_frame, end_frame)

        # HR sequence
        stem = Path(video_path).stem
        hr_df, hr_col = cached_hr_df(stem)
        hr_seq = extract_hr_seq(hr_df, hr_col, start_sec, end_sec, step=1.0)
        # Pad/truncate HR to a fixed length, e.g., 4 samples
        HR_LEN = 4
        if len(hr_seq) < HR_LEN:
            pad = np.full(HR_LEN - len(hr_seq), hr_seq[-1], dtype=np.float32)
            hr_seq_fixed = np.concatenate([hr_seq, pad])
        else:
            hr_seq_fixed = hr_seq[:HR_LEN]
        hr_seq_fixed = hr_seq_fixed.astype(np.float32)

        # Targets
        hr_class   = np.int32(r["hr_class"])
        diff_class = np.int32(r["diff_class"])
        perf_reg   = np.float32(r["perf"])

        yield (clip, hr_seq_fixed), (hr_class, diff_class, perf_reg)

T = N_FRAMES
H, W = IMG_SIZE
HR_LEN = 4

input_sig = (
    (
        tf.TensorSpec((T, H, W, 3), tf.float32),      # video
        tf.TensorSpec((HR_LEN,), tf.float32)          # HR sequence
    ),
    (
        tf.TensorSpec((), tf.int32),                  # hr_class
        tf.TensorSpec((), tf.int32),                  # diff_class
        tf.TensorSpec((), tf.float32)                 # perf_reg
    )
)

def make_dataset(records, shuffle=True):
    ds = tf.data.Dataset.from_generator(
        lambda: multimodal_generator(records),
        output_signature=input_sig
    )
    if shuffle:
        ds = ds.shuffle(1024, seed=SEED)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds

train_ds = make_dataset(train_records, shuffle=True)
val_ds   = make_dataset(val_records,   shuffle=False)
test_ds  = make_dataset(test_records,  shuffle=False)

def build_video_branch():
    # Frame encoder: small MobileNetV2 (or EfficientNetB0)
    base = tf.keras.applications.MobileNetV2(
        input_shape=(H, W, 3),
        include_top=False,
        weights="imagenet"
    )
    base.trainable = False  # fine-tune later if needed

    i = layers.Input((T, H, W, 3))
    # Apply base CNN per frame
    x = layers.TimeDistributed(base)(i)
    x = layers.TimeDistributed(layers.GlobalAveragePooling2D())(x)  # (B, T, D)

    # Temporal Conv1D
    x = layers.Conv1D(64, kernel_size=3, padding="same", activation="relu")(x)
    x = layers.Conv1D(64, kernel_size=3, padding="same", activation="relu")(x)
    x = layers.GlobalAveragePooling1D()(x)  # (B, 64)

    x = layers.Dense(64, activation="relu")(x)
    return models.Model(i, x, name="video_branch")

def build_hr_branch():
    i = layers.Input((HR_LEN,))
    x = layers.Reshape((HR_LEN, 1))(i)
    x = layers.Conv1D(16, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(32, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dense(32, activation="relu")(x)
    return models.Model(i, x, name="hr_branch")

def build_multimodal_model():
    video_in = layers.Input((T, H, W, 3), name="video_in")
    hr_in    = layers.Input((HR_LEN,),    name="hr_in")

    video_branch = build_video_branch()
    hr_branch    = build_hr_branch()

    z_v  = video_branch(video_in)
    z_hr = hr_branch(hr_in)

    # Gated fusion
    concat = layers.Concatenate()([z_v, z_hr])
    g = layers.Dense(64, activation="sigmoid")(concat)
    # ensure g has same dim as z_v / z_hr; adjust to 64
    z_v_proj  = layers.Dense(64)(z_v)
    z_hr_proj = layers.Dense(64)(z_hr)

    fused = g * z_v_proj + (1.0 - g) * z_hr_proj
    fused = layers.Dense(64, activation="relu")(fused)

    # Heads
    hr_out = layers.Dense(NUM_HR_CLASSES, activation="softmax", name="hr_intensity")(fused)
    diff_out = layers.Dense(NUM_DIFF_CLASSES, activation="softmax", name="diff_proxy")(fused)
    perf_out = layers.Dense(1, activation="linear", name="perf_reg")(fused)

    model = models.Model(
        inputs=[video_in, hr_in],
        outputs=[hr_out, diff_out, perf_out],
        name="bio_exergame_multimodal"
    )

    losses_dict = {
        "hr_intensity": losses.SparseCategoricalCrossentropy(),
        "diff_proxy":   losses.SparseCategoricalCrossentropy(),
        "perf_reg":     losses.MeanSquaredError()
    }

    loss_weights = {
        "hr_intensity": 1.0,
        "diff_proxy":   1.0,
        "perf_reg":     0.5
    }

    model.compile(
        optimizer=optimizers.Adam(1e-4),
        loss=losses_dict,
        loss_weights=loss_weights,
        metrics={
            "hr_intensity": "accuracy",
            "diff_proxy":   "accuracy",
            "perf_reg":     tf.keras.metrics.MeanAbsoluteError()
        }
    )

    return model

model = build_multimodal_model()
model.summary()

import tensorflow as tf

def map_to_named_outputs(inputs, targets):
    # inputs:  (video, hr_seq)
    # targets: (hr_class, diff_class, perf_reg)
    video, hr_seq = inputs
    hr_class, diff_class, perf_reg = targets

    x = {
        "video_in": video,
        "hr_in":    hr_seq
    }
    y = {
        "hr_intensity": hr_class,
        "diff_proxy":   diff_class,
        "perf_reg":     tf.expand_dims(perf_reg, -1)
    }
    return x, y

train_ds_named = train_ds.map(
    map_to_named_outputs,
    num_parallel_calls=tf.data.AUTOTUNE
)
val_ds_named = val_ds.map(
    map_to_named_outputs,
    num_parallel_calls=tf.data.AUTOTUNE
)
test_ds_named = test_ds.map(
    map_to_named_outputs,
    num_parallel_calls=tf.data.AUTOTUNE
)

for elem in train_ds.take(1):
    print(tf.nest.map_structure(lambda t: (t.shape, t.dtype), elem))

cbs = [
    callbacks.EarlyStopping(patience=6, restore_best_weights=True),
    callbacks.ReduceLROnPlateau(patience=3, factor=0.5, verbose=1)
]

history = model.fit(
    train_ds_named,
    validation_data=val_ds_named,
    epochs=EPOCHS,
    callbacks=cbs,
    verbose=2
)

import matplotlib.pyplot as plt

print(history.history.keys())

def plot_metric(history, metric, title=None):
    plt.figure()
    plt.plot(history.history[metric], label=f"train_{metric}")
    plt.plot(history.history["val_" + metric], label=f"val_{metric}")
    plt.xlabel("Epoch")
    plt.ylabel(metric)
    if title:
        plt.title(title)
    else:
        plt.title(metric)
    plt.legend()
    plt.grid(True)
    plt.show()

# 1. HR intensity accuracy
plot_metric(history, "hr_intensity_accuracy", title="HR Intensity Accuracy")

# 2. Difficulty/load proxy accuracy
plot_metric(history, "diff_proxy_accuracy", title="Difficulty Proxy Accuracy")

# 3. Overall loss
plt.figure()
plt.plot(history.history["loss"], label="train_loss")
plt.plot(history.history["val_loss"], label="val_loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Total Loss")
plt.legend()
plt.grid(True)
plt.show()

# 4. Optional: performance regression MAE
plot_metric(history, "perf_reg_mean_absolute_error", title="Performance MAE")

model.evaluate(test_ds_named, verbose=2)

"""## Training for Longer Epochs"""

cbs = [
    callbacks.EarlyStopping(patience=6, restore_best_weights=True),
    callbacks.ReduceLROnPlateau(patience=3, factor=0.5, verbose=1)
]

history = model.fit(
    train_ds_named,
    validation_data=val_ds_named,
    epochs=50,
    callbacks=cbs,
    verbose=2
)

import matplotlib.pyplot as plt

def plot_metric(history, metric, title=None):

    plt.figure()
    plt.plot(history.history[metric], label=f"train_{metric}")
    plt.plot(history.history["val_" + metric], label=f"val_{metric}")
    plt.xlabel("Epoch")
    plt.ylabel(metric)
    if title:
        plt.title(title)
    else:
        plt.title(metric)
    plt.legend()
    plt.grid(True)
    plt.show()

# 1. HR intensity accuracy
plot_metric(history, "hr_intensity_accuracy", title="HR Intensity Accuracy")

# 2. Difficulty/load proxy accuracy
plot_metric(history, "diff_proxy_accuracy", title="Difficulty Proxy Accuracy")

# 3. Overall loss
plt.figure()
plt.plot(history.history["loss"], label="train_loss")
plt.plot(history.history["val_loss"], label="val_loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Total Loss")
plt.legend()
plt.grid(True)
plt.show()

# 4. Optional: performance regression MAE
plot_metric(history, "perf_reg_mean_absolute_error", title="Performance MAE")

model.evaluate(test_ds_named, verbose=2)